### ISSUE TITLE
Issues with Python package installation

### ISSUE THREAD

**Issue by ttszen** [digitalcytometry/cytotrace2#2]
Hello! Thank you very much for the interesting package! I'm really interested in using it for my scRNA-seq data. 

I'm using conda 4.9.2 and trying to run the installation for the Python version of Cytotrace2. Unfortunately I have been getting the following warnings when I use the `environment_py.yml` file. The process is still stuck in Solving environment. 

```
Collecting package metadata (repodata.json): \ WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(537): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.6.0.*, but conda is ignoring the .* and treating it as 1.6.0
done
Solving environment: 
```

Do you have any recommendations to solve this problem? 

It'd be great to get your thoughts and happy to discuss further!

**Comment by savagyan00** [comment]
Hi and thank you for your interest in trying CytoTRACE 2!

The warnings you’ve encountered should not indicate any issues that would inherently prevent the environment from solving. These warnings essentially inform you about a deprecated syntax or behavior in Conda but don’t significantly affect the environment setup process.

While we were unable to replicate this issue for the CytoTRACE 2 environment file, we have seen other Conda environments where a seemingly stuck process can be solved given enough time (e.g., ~1 hr). That said, if the solving time is unreasonably long, you might consider updating Conda to address the issue. The newer versions often come with improvements to the dependency resolver, which might help reduce solve times. Conda can be updated by running:

`conda update -n base -c defaults conda`

If the environment still fails to solve, please let us know!

**Comment by ttszen** [comment]
Hi @savagyan00, thanks so much for the clarification. That makes sense to me. I will give it another try and give it more time. I gave it around 40 mins the last time I tried. 

I'll implement your suggestion if that doesn't work again and keep you all updated. I've tried the package in R and it runs smoothly there!
