### ISSUE TITLE
Cytotrace2_py without R dependency

### ISSUE THREAD

**Issue by Starlitnightly** [digitalcytometry/cytotrace2#20]
Hi, I rewrote `smoothDatakNN.R` in Python, and the associated plotting was implemented using `scanpy.pl`, so I can submit a Pull Request if you guys need it.

Zehua

<img width="847" alt="image" src="https://github.com/digitalcytometry/cytotrace2/assets/46667721/aa84a5b7-2a74-4592-aa43-bc440c809211">

**Comment by savagyan00** [comment]
Hi,

Thank you so much for using CytoTRACE 2 and your effort in rewriting `smoothDatakNN.R` in Python. We really appreciate your initiative to enhance the tool's capabilities and will definitely review your pull request soon. Our team is continuously working on improving the tool, and we are excited to integrate our efforts for a better outcome for the whole community.

We hope our tool continues to be useful in your work. Let us know in case of any questions at any time!

**Comment by Starlitnightly** [comment]
> Hi,
> 
> Thank you so much for using CytoTRACE 2 and your effort in rewriting `smoothDatakNN.R` in Python. We really appreciate your initiative to enhance the tool's capabilities and will definitely review your pull request soon. Our team is continuously working on improving the tool, and we are excited to integrate our efforts for a better outcome for the whole community.
> 
> We hope our tool continues to be useful in your work. Let us know in case of any questions at any time!

I've added the `smoothDatakNN.py` file, and for the adata input, it doesn't quite match the cytotrace2 expression input format, and I'm worried about changing it too much in package!

Zehua
