### ISSUE TITLE
can there have a conda env of R version

### ISSUE THREAD

**Issue by asmlgkj** [digitalcytometry/cytotrace2#22]
Thans a lot
devtools::install_github("digitalcytometry/cytotrace2", subdir = "cytotrace2_r")

make: *** [lib/R/etc/Makeconf:200: RcppExports.o] Error 1
ERROR: compilation failed for package ‘RcppGSL’
* removing ‘lib/R/library/RcppGSL’

**Comment by savagyan00** [comment]
Hi and thanks for using CytoTRACE 2!

We do provide a conda environment for the R package, which you can find with a conda environment file [here](https://github.com/digitalcytometry/cytotrace2/blob/main/environment_R.yml).

To create and activate this conda environment you can follow these steps:

- Install [Miniconda](https://docs.conda.io/projects/conda/en/latest/user-guide/install/index.html) if not already available.
- (5-10 minutes) Create a conda environment with the required dependencies:
` conda env create -f environment_R.yml`
- Activate the cytotrace2 environment you just created:
`conda activate cytotrace2`

Please let us know if this works out for you, and if you have any further questions!

**Comment by asmlgkj** [comment]
Thanks a lot. you helped me a lot

**Comment by savagyan00** [comment]
Hi,
We are glad to hear our response was helpful.
Please feel free to reach out if you need further assistance or have any other questions!
