### ISSUE TITLE
Errors for Compute transition matrix by using `ctk = ctk.compute_cytotrace().compute_transition_matrix(scheme="soft", nu=0.5)`

### ISSUE THREAD

**Issue by mainharryHR** [digitalcytometry/cytotrace2#24]
Dear Team, 

I used and R and get the reasonable results, When I tried to combine the CellRank to make pseudotime by the following code, It give me different results which does not make sense to me. I am wondering which parameter I could use to adjust?

Thank you all very much.

`ctk = cr.kernels.CytoTRACEKernel(adata)`
`ckt = ctk.compute_cytotrace().compute_transition_matrix()`

**Comment by savagyan00** [comment]
Hello and thanks for reaching out,

CytoTRACE is another algorithm from our group, that is different from the CytoTRACE 2 tool on this GitHub page. The CellRank team has adapted CytoTRACE implementation as one of their tool's underlying kernels. If CytoTRACE run by itself works as expected and you see an issue with the results that CellRank has provided, it might be useful to post this question on CellRank's GitHub page.

If you also try out CytoTRACE 2 and there are any questions related to it, feel free to reach out!

**Comment by mainharryHR** [comment]
> Hello and thanks for reaching out,
> 
> CytoTRACE is another algorithm from our group, that is different from the CytoTRACE 2 tool on this GitHub page. The CellRank team has adapted CytoTRACE implementation as one of their tool's underlying kernels. If CytoTRACE run by itself works as expected and you see an issue with the results that CellRank has provided, it might be useful to post this question on CellRank's GitHub page.
> 
> If you also try out CytoTRACE 2 and there are any questions related to it, feel free to reach out!

Thank you for the fast reply. I though they are using the same algorithm. CytoTRACE gives me reasonable results, I was thinking to plot the pseudotime in the UMAP as well. It is not easy for me to get the unspliced RNA for the seurat object. 

I appreciate your kind help.
Best

**Comment by savagyan00** [comment]
Hello, 

We noticed that the CellRank team has addressed your questions regarding the CytoTRACE kernel of the CellRank package on their GitHub page. As we don't have any unresolved questions regarding CytoTRACE 2 I am closing this issue.

If you find CytoTRACE 2 useful for your work and have any questions about it, please don't hesitate to reach out.
