### ISSUE TITLE
Bug / potential fix in utils

### ISSUE THREAD

**Issue by ryzhalex** [digitalcytometry/cytotrace2#27]
Hello,

I am running a dataset through the python version of the program.

cytotrace2_python/cytotrace2_py/common/gen_utils.py was throwing the error on line 121
`idx = [unmapped_genes[i.upper()] for i in duplicate_genes if i.upper() in unmapped_genes.keys()]`
float does not have a function upper()

Apparently for some reason variable i was getting float value.

I did not dig deeply, but as far as I understood variable i should be a name of gene, so I casted str on the variable, which resolved the issue.

`idx = [unmapped_genes[str(i).upper()] for i in duplicate_genes if str(i).upper() in unmapped_genes.keys()]  `

**Comment by savagyan00** [comment]
Hi! Thank you for using CytoTRACE 2, and reporting this issue with your solution!

Generally, the gene names passed as rownames in the expression matrix are expected to be strings, not numeric values. Is this true for your dataset? Converting gene names (rownames) to strings before passing the expression matrix to the function can be a preventive measure to avoid such errors.
Your solution of explicitly casting the gene names to strings within the list comprehension is perfectly valid and effectively handles this scenario. We appreciate your contribution and will include handling this edge case in our future releases!

Thanks again for your feedback and support. Let us know if we can help with anything else!
