### ISSUE TITLE
Issue report about BrokenProcessPool

### ISSUE THREAD

**Issue by dicklim** [digitalcytometry/cytotrace2#29]
Hi, I am running Cytotrace for the second time, and a 'BrokenProcessPool' error happened.
I have no idea how this happened. I tried to restrict the core num to 1, but it doesn't work. But I tried to run 'process_subset' without using 'executor.submit' and it works.
So can you help to find out what happed?

Here is my Error:

```
BrokenProcessPool                         Traceback (most recent call last)
Cell In[44], line 3
      2 example_species = "human"
----> 3 results =  cytotrace2_py.cytotrace2_py.cytotrace2(
      4     mtx_neww,
      5     # annotation_path=example_annotation_path,
      6 #     max_cores =2,
      7     batch_size=1000,
      8 #     smooth_batch_size=2000,
      9     species=example_species
     10 )

File ~/anaconda3/envs/scRNA/lib/python3.9/site-packages/cytotrace2_py/cytotrace2_py.py:173, in cytotrace2(input_data, annotation_path, species, full_model, batch_size, smooth_batch_size, disable_parallelization, max_cores, max_pcs, seed, output_dir)
    171 for f in concurrent.futures.as_completed(results):
    172     print(f)
--> 173     smooth_by_knn_df = f.result()
    174     print(smooth_by_knn_df)
    175     predictions.append(smooth_by_knn_df)

File ~/anaconda3/envs/scRNA/lib/python3.9/concurrent/futures/_base.py:439, in Future.result(self, timeout)
    437     raise CancelledError()
    438 elif self._state == FINISHED:
--> 439     return self.__get_result()
    441 self._condition.wait(timeout)
    443 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File ~/anaconda3/envs/scRNA/lib/python3.9/concurrent/futures/_base.py:391, in Future.__get_result(self)
    389 if self._exception:
    390     try:
--> 391         raise self._exception
    392     finally:
    393         # Break a reference cycle with the exception in self._exception
    394         self = None

BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

**Comment by dicklim** [comment]
Well Seems that the `concurrent.futures.ProcessPoolExecutor` (cytotrace2_py/cytotrace2_py.py:171) could not run well in a Jupyter Notebook. I changed it to `concurrent.futures.ThreadPoolExecutor` and it works now.

**Comment by savagyan00** [comment]
Thank you for reaching out and sharing your solution.

Switching to `ThreadPoolExecutor` indeed can be a practical workaround for this issue, which is specific to the Jupyter Notebook environment. However, it's important to note that while this approach gets things working, it may not be ideal for CPU-bound tasks. Alternatively, you can use the command line option of the Python implementation or the R implementation of the package.

We recognize the importance of optimizing performance for different environments, including Jupyter Notebooks. In our future releases, we will explore more effective solutions to this issue.

Your feedback is invaluable, and we're committed to improving our tool. Thank you for your patience and support as we work on these enhancements.
