### ISSUE TITLE
CytoTRACE2_Score vs CytoTRACE2_relative

### ISSUE THREAD

**Issue by hansong798** [digitalcytometry/cytotrace2#3]
Hello, thanks for the wonderful tool, but I have a question about interpretation.

I want to compare the stemness of specific cells between groups.
I noted that the results are different depending on the CytoTRACE2_Score or CytoTRACE2_relative.

CytoTRACE2_Score gives a higher level of stemness in the A group,
but CytoTRACE2_relative gives it in the B group, which is generally known to be higher.

Which score is proper to compare the groups?
Is it okay to use CytoTRACE2_relative?

**Comment by savagyan00** [comment]
Hi and thank you for trying out CytoTRACE 2! 

To better assist you, it would be helpful to know more about your dataset, the labels for the groups you're comparing, the summary metric used for comparison, and how predictions for these groups appear on an absolute scale (CytoTRACE2_Score).

The relative score in CytoTRACE 2 is derived from ranking and scaling absolute scores to a [0,1] range. Typically, both scores can be used to compare groups within the same dataset, reflecting a similar hierarchy for aggregated values across cell types/groups. However, using the mean as a summary statistic is not recommended to compare relative scores, as those are in rank space. Instead, the median might offer a clearer comparison.

If you don't mind providing more information, perhaps sharing your dataset and results with us, via [cytotrace2team@gmail.com](mailto:cytotrace2team@gmail.com), we can further investigate and happily help interpret the results.

**Comment by hansong798** [comment]
Thanks for tour kind reply.

I've run Cytotrace2 on combined and separate control and tumor dataset
respectively.
The cancer cells from control group had higher cytotrace2 score when run on
combined datase, while using separate dataset, cancer cell from tumor
dataset had high relative cytotrace2 score.

Is it right way to compare the relative score across dataset?


*Hansong Lee*
Pusan National University,
Mobile: +82-10-4146-1164


2024년 4월 6일 (토) 오전 2:38, savagyan00 ***@***.***>님이 작성:

**Comment by savagyan00** [comment]
Thanks for the clarification. Relative scores are designed to provide insights within the context of a single dataset, as the values are scaled given the range of predicted absolute scores within that dataset. For meaningful comparisons of CytoTRACE 2 results between different conditions or datasets, we recommend running CytoTRACE 2 separately over each dataset and using CytoTRACE2_Score.

You can refer to item 4 of the "Frequently asked questions" section in our [README](https://github.com/digitalcytometry/cytotrace2/tree/main). Let us know if further clarification and help is needed!
