### ISSUE TITLE
Gene Signature Rankings

### ISSUE THREAD

**Issue by e-arslan** [digitalcytometry/cytotrace2#32]
Is there a way to calculate  a ranked list of genes associated with differentiation states w/ CytoTRACE 2 ?

**Comment by savagyan00** [comment]
Hi and thank you for using CytoTRACE 2,

While direct functionality for calculating correlation of individual genes with CytoTRACE 2 predicted scores isn't currently provided by the package, you can use the following R code (using the library ccaPP) to achieve the result you are interested in:

```
library(ccaPP)
# Assuming 'gene_expression_data' is your matrix of genes (rows) by samples (columns)
# and 'cytotrace2_score' is the vector of CytoTRACE 2 scores

# Calculate Pearson correlation between each gene and the CytoTRACE 2 scores
ct2genes <- sapply(1:nrow(gene_expression_data),
                     function(x) ccaPP::corPearson(gene_expression_data[x,], cytotrace2_score))
names(ct2genes) <- rownames(gene_expression_data)

# Sort by decreasing order of correlation
ct2_gene_correlations <- sort(ct2genes, decreasing = TRUE)
```

This code will provide a list of genes ordered by their correlation to the inferred CytoTRACE 2 scores.
Feel free to reach out if you need further assistance!

**Comment by savagyan00** [comment]
Hi @e-arslan ,

Just wanted to follow up on the issue you were experiencing with CytoTRACE 2. We hope our suggestion has been helpful. Since we haven't heard back, I'm going to close the issue for now. Please feel free to respond and reopen it if you need further assistance or if the problem persists. 

Thanks!
