### ISSUE TITLE
Why the "species" only support human or mouse？

### ISSUE THREAD

**Issue by Lighter-k** [digitalcytometry/cytotrace2#34]
I study plants. Can I define species myself?  Or offer options for more species.

**Comment by savagyan00** [comment]
Hi and thank you for your interest in CytoTRACE 2!

CytoTRACE 2 was specifically developed for use with mouse and human data, and it accepts gene names in MGI and HGNC nomenclatures accordingly. It has not been trained or tested on plant data, which means the potency-related information that the model has learned and is using to predict new datasets, is strongly associated with the biology of humans, mouse, and other species that are "orthologously" close to these two. Consequently, in the case of plants, the tool might not be fit.

Sorry for the inconvenience. Please let us know if we can assist you further!
