### ISSUE TITLE
Inconsistent Results Using Example Data and Code

### ISSUE THREAD

**Issue by Svvord** [digitalcytometry/cytotrace2#36]
Hi, very interesting work. However, some weird problem happened while I was using it. I used the example data and code exactly as provided, but the results are completely different.
![Screenshot 2024-09-23 at 17 28 32](https://github.com/user-attachments/assets/344ec8a7-8bf6-47a4-b392-9aca1b1f9aaa)

**Comment by savagyan00** [comment]
Hi,

Thank you for your interest in CytoTRACE 2 and for sharing your experience! 
Differences in package versions can indeed cause some discrepancies. We are glad using author-provided versions worked for you. Still, for troubleshooting purposes, we would really appreciate it if you could please share any error messages or warnings that appeared while running the code initially, and also, your sessionInfo() containing the package versions for that run.

We would appreciate your collaboration!
