### ISSUE TITLE
Cytotrace2 with other species

### ISSUE THREAD

**Issue by gomezcan** [digitalcytometry/cytotrace2#38]
Hi, 

I wonder, Can cytrotrace2 be applied to data from species other than human and mouse?

Thanks

**Comment by savagyan00** [comment]
Hi and thank you for your interest in CytoTRACE 2!

CytoTRACE 2 was specifically developed for use on mouse and human data, and it accepts gene names in MGI and HGNC nomenclatures accordingly. It has not been trained or tested on other species' data, which means the potency-related information that the model has learned and is using to predict new datasets is strongly associated with the biology of humans and mice, and can be somewhat associated with other species that are "orthologously" close to these two. If you find your species to be one of the latter, you can give it a try, although we cannot guarantee accuracy.

Please let us know if we can assist with anything else!
