### ISSUE TITLE
Adding custom colour gradient for potency score

### ISSUE THREAD

**Issue by calvin-s-rodrigues** [digitalcytometry/cytotrace2#39]
Hello, thanks for a great and easy to use package! 
I would like to ask, is there any way to add a custom colour gradient for the potency score UMAP? While also retaining the cell category legend? 

Here is the original plot, but the yellow cells are not well distinguishable from the white background.

plots$CytoTRACE2_UMAP

![image](https://github.com/user-attachments/assets/e11c0012-8ce3-45ae-9012-589aa92e20fe)

I tried the following, which gives a different colour scale, but this removes the legend giving the potency categories
plots$CytoTRACE2_UMAP+
  scale_colour_gradientn(colours=c("navyblue", "darkmagenta", "darkorange1"))

![image](https://github.com/user-attachments/assets/3d4870df-bc86-4861-b571-b8216dcf73df)

Thank you!

**Comment by savagyan00** [comment]
Hi and thank you for using CytoTRACE 2!

You can change the coloring scheme with the following code:

```
labels <- c('Differentiated', 'Unipotent', 'Oligopotent', 'Multipotent', 'Pluripotent', 'Totipotent')
colors <- c("navyblue", "darkmagenta", "darkorange1") # or any other color vector
plots$CytoTRACE2_UMAP + scale_colour_gradientn(colours = colors, na.value = "transparent",
                                                    labels = c(labels),
                                                    limits=c(-5,0), name = "Potency score \n",
                                                    guide = guide_colorbar(frame.colour = "black", ticks.colour = "black"))
```

However, I would advise using a six-color vector for your colors so that it's easier to visually tell apart the predicted potency categories on the continuous score UMAP.

Let us know if we can assist with any other questions!

**Comment by calvin-s-rodrigues** [comment]
Okay this is great, many thanks for your help and advice!
